// <auto-generated />
using System;
using Infrastructure.Data.Persistent;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AnonymizationCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RetentionPolicyId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SuggestedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ResidentId");

                    b.HasIndex("RetentionPolicyId");

                    b.ToTable("AnonymizationCandidates");
                });

            modelBuilder.Entity("Domain.Entities.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("EndTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("AuditEntries");
                });

            modelBuilder.Entity("Domain.Entities.ChangeDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AuditEntryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("AuditEntryId")
                        .HasDatabaseName("IX_ChangeDetails_AuditEntryId");

                    b.ToTable("ChangeDetails");
                });

            modelBuilder.Entity("Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Employees_UserId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            Department = 0,
                            FirstName = "Peder",
                            Initials = "PR",
                            LastName = "Rasmussen",
                            UserId = new Guid("3a21f8e1-885b-4394-abf0-ed0baeea239b")
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            Department = 0,
                            FirstName = "Sanne",
                            Initials = "SJ",
                            LastName = "Johansen",
                            UserId = new Guid("4711a300-711e-4132-86d4-cafd3f11deec")
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            Department = 0,
                            FirstName = "Thor",
                            Initials = "TD",
                            LastName = "Danrsøn",
                            UserId = new Guid("30cffcf9-5784-4fa9-9c10-c013ef3faf16")
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000004"),
                            Department = 1,
                            FirstName = "Per",
                            Initials = "PN",
                            LastName = "Nielsen",
                            UserId = new Guid("37155b80-7111-422a-aba6-89d7070f1644")
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000005"),
                            Department = 1,
                            FirstName = "Anders",
                            Initials = "AJ",
                            LastName = "Jensen",
                            UserId = new Guid("b836e975-e775-48bc-8b84-5d2bdd5bd87a")
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000006"),
                            Department = 2,
                            FirstName = "Kasper",
                            Initials = "KH",
                            LastName = "Holm",
                            UserId = new Guid("48245a9c-f2a5-4e8f-9554-b6acc9206d37")
                        });
                });

            modelBuilder.Entity("Domain.Entities.LoginAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmailHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedAt");

                    b.HasIndex("EmailHash", "AttemptedAt");

                    b.HasIndex("IpAddress", "AttemptedAt");

                    b.ToTable("LoginAttempts");
                });

            modelBuilder.Entity("Domain.Entities.MedicineRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Given")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ResidentId");

                    b.ToTable("MedicineRecord");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0684cf2-f249-41f6-af83-0a75e0a5e7d3"),
                            Given = true,
                            MedicineName = "Atenolol",
                            ResidentId = new Guid("694b9796-dc5a-4a68-bafb-0a59595e8fb3"),
                            Timestamp = new DateTime(2026, 4, 1, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c9f94fc6-c542-4ae9-ade6-3c40cd2262d8"),
                            Given = true,
                            MedicineName = "Sertraline",
                            ResidentId = new Guid("694b9796-dc5a-4a68-bafb-0a59595e8fb3"),
                            Timestamp = new DateTime(2026, 4, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4bbd018f-b297-4973-85e9-5be5b0499834"),
                            Given = false,
                            MedicineName = "Bisoprolol",
                            ResidentId = new Guid("d3e4f5a6-7890-1234-5678-9abcdef01234"),
                            Timestamp = new DateTime(2026, 4, 2, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c9f58ba2-c394-4f8c-b058-c13766689c79"),
                            Given = false,
                            MedicineName = "Quetiapine",
                            ResidentId = new Guid("f5a6b7c8-9012-3456-789a-bcdef0123456"),
                            Timestamp = new DateTime(2026, 4, 2, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Domain.Entities.PainkillerRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("GivenAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NextAllowedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ResidentId");

                    b.ToTable("PainkillerRecord");
                });

            modelBuilder.Entity("Domain.Entities.PhoneAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CaregiverId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PhoneAssignments");
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("TokenHash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Domain.Entities.Resident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DischargedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("TrafficLightStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Residents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("694b9796-dc5a-4a68-bafb-0a59595e8fb3"),
                            Department = 0,
                            FirstName = "Anna",
                            Initials = "AA",
                            LastName = "Andersen",
                            TrafficLightStatus = 0
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-1234-56789abcdef0"),
                            Department = 0,
                            FirstName = "Birthe",
                            Initials = "BB",
                            LastName = "Brun",
                            TrafficLightStatus = 2
                        },
                        new
                        {
                            Id = new Guid("c2d3e4f5-6789-0123-4567-89abcdef0123"),
                            Department = 0,
                            FirstName = "Carl",
                            Initials = "CC",
                            LastName = "Christensen",
                            TrafficLightStatus = 1
                        },
                        new
                        {
                            Id = new Guid("d3e4f5a6-7890-1234-5678-9abcdef01234"),
                            Department = 0,
                            FirstName = "Dorthe",
                            Initials = "DD",
                            LastName = "Dalgaard",
                            TrafficLightStatus = 0
                        },
                        new
                        {
                            Id = new Guid("e4f5a6b7-8901-2345-6789-abcdef012345"),
                            Department = 0,
                            FirstName = "Erik",
                            Initials = "EE",
                            LastName = "Eriksen",
                            TrafficLightStatus = 0
                        },
                        new
                        {
                            Id = new Guid("f5a6b7c8-9012-3456-789a-bcdef0123456"),
                            Department = 0,
                            FirstName = "Frida",
                            Initials = "FF",
                            LastName = "Frederiksen",
                            TrafficLightStatus = 1
                        },
                        new
                        {
                            Id = new Guid("a6b7c8d9-0123-4567-89ab-cdef01234567"),
                            Department = 0,
                            FirstName = "Gunnar",
                            Initials = "GG",
                            LastName = "Gregersen",
                            TrafficLightStatus = 0
                        },
                        new
                        {
                            Id = new Guid("b7c8d9e0-1234-5678-9abc-def012345678"),
                            Department = 0,
                            FirstName = "Hanne",
                            Initials = "HH",
                            LastName = "Hansen",
                            TrafficLightStatus = 2
                        },
                        new
                        {
                            Id = new Guid("c8d9e0f1-2345-6789-abcd-ef0123456789"),
                            Department = 0,
                            FirstName = "Ida",
                            Initials = "II",
                            LastName = "Iversen",
                            TrafficLightStatus = 0
                        },
                        new
                        {
                            Id = new Guid("d9e0f1a2-3456-789a-bcde-f01234567890"),
                            Department = 0,
                            FirstName = "Jens",
                            Initials = "JJ",
                            LastName = "Jensen",
                            TrafficLightStatus = 0
                        },
                        new
                        {
                            Id = new Guid("e0f1a2b3-4567-89ab-cdef-012345678901"),
                            Department = 0,
                            FirstName = "Karen",
                            Initials = "KK",
                            LastName = "Knudsen",
                            TrafficLightStatus = 2
                        },
                        new
                        {
                            Id = new Guid("f1a2b3c4-5678-9abc-def0-123456789012"),
                            Department = 0,
                            FirstName = "Lars",
                            Initials = "LL",
                            LastName = "Larsen",
                            TrafficLightStatus = 1
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000001"),
                            Department = 1,
                            FirstName = "Mette",
                            Initials = "MM",
                            LastName = "Madsen",
                            TrafficLightStatus = 0
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000002"),
                            Department = 1,
                            FirstName = "Niels",
                            Initials = "NN",
                            LastName = "Nielsen",
                            TrafficLightStatus = 1
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000003"),
                            Department = 1,
                            FirstName = "Ole",
                            Initials = "OO",
                            LastName = "Olesen",
                            TrafficLightStatus = 2
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000004"),
                            Department = 1,
                            FirstName = "Pia",
                            Initials = "PP",
                            LastName = "Petersen",
                            TrafficLightStatus = 0
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000005"),
                            Department = 1,
                            FirstName = "Rasmus",
                            Initials = "RR",
                            LastName = "Rasmussen",
                            TrafficLightStatus = 0
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000006"),
                            Department = 1,
                            FirstName = "Sofie",
                            Initials = "SS",
                            LastName = "Sørensen",
                            TrafficLightStatus = 1
                        },
                        new
                        {
                            Id = new Guid("aa000001-0000-0000-0000-000000000007"),
                            Department = 1,
                            FirstName = "Thomas",
                            Initials = "TT",
                            LastName = "Thomsen",
                            TrafficLightStatus = 2
                        },
                        new
                        {
                            Id = new Guid("bb000002-0000-0000-0000-000000000001"),
                            Department = 2,
                            FirstName = "Ulla",
                            Initials = "UU",
                            LastName = "Ulrichsen",
                            TrafficLightStatus = 0
                        },
                        new
                        {
                            Id = new Guid("bb000002-0000-0000-0000-000000000002"),
                            Department = 2,
                            FirstName = "Viggo",
                            Initials = "VV",
                            LastName = "Vestergaard",
                            TrafficLightStatus = 2
                        },
                        new
                        {
                            Id = new Guid("bb000002-0000-0000-0000-000000000003"),
                            Department = 2,
                            FirstName = "Winnie",
                            Initials = "WW",
                            LastName = "Winther",
                            TrafficLightStatus = 1
                        },
                        new
                        {
                            Id = new Guid("bb000002-0000-0000-0000-000000000004"),
                            Department = 2,
                            FirstName = "Xenia",
                            Initials = "XX",
                            LastName = "Xu",
                            TrafficLightStatus = 0
                        },
                        new
                        {
                            Id = new Guid("bb000002-0000-0000-0000-000000000005"),
                            Department = 2,
                            FirstName = "Yvonne",
                            Initials = "YY",
                            LastName = "Yilmaz",
                            TrafficLightStatus = 0
                        },
                        new
                        {
                            Id = new Guid("bb000002-0000-0000-0000-000000000006"),
                            Department = 2,
                            FirstName = "Zenia",
                            Initials = "ZZ",
                            LastName = "Zahle",
                            TrafficLightStatus = 2
                        },
                        new
                        {
                            Id = new Guid("bb000002-0000-0000-0000-000000000007"),
                            Department = 2,
                            FirstName = "Bent",
                            Initials = "BA",
                            LastName = "Bagger",
                            TrafficLightStatus = 0
                        },
                        new
                        {
                            Id = new Guid("bb000002-0000-0000-0000-000000000008"),
                            Department = 2,
                            FirstName = "Connie",
                            Initials = "CO",
                            LastName = "Christoffersen",
                            TrafficLightStatus = 1
                        },
                        new
                        {
                            Id = new Guid("bb000002-0000-0000-0000-000000000009"),
                            Department = 2,
                            FirstName = "Dagmar",
                            Initials = "DA",
                            LastName = "Damgaard",
                            TrafficLightStatus = 0
                        });
                });

            modelBuilder.Entity("Domain.Entities.ResidentNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EditedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ResidentId")
                        .HasDatabaseName("IX_ResidentNotes_ResidentId");

                    b.ToTable("ResidentNotes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f5a6b7c8-9012-3456-7890-abcdef012345"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident A's note.",
                            ResidentId = new Guid("694b9796-dc5a-4a68-bafb-0a59595e8fb3")
                        },
                        new
                        {
                            Id = new Guid("a6b7c8d9-0123-4567-8901-bcdef0123456"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident B's note.",
                            ResidentId = new Guid("a1b2c3d4-e5f6-7890-1234-56789abcdef0")
                        },
                        new
                        {
                            Id = new Guid("b7c8d9e0-1234-5678-9012-cdef01234567"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident C's note.",
                            ResidentId = new Guid("c2d3e4f5-6789-0123-4567-89abcdef0123")
                        },
                        new
                        {
                            Id = new Guid("c8d9e0f1-2345-6789-0123-def012345678"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident D's note.",
                            ResidentId = new Guid("d3e4f5a6-7890-1234-5678-9abcdef01234")
                        },
                        new
                        {
                            Id = new Guid("d9e0f1a2-3456-7890-1234-ef0123456789"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident E's note.",
                            ResidentId = new Guid("e4f5a6b7-8901-2345-6789-abcdef012345")
                        },
                        new
                        {
                            Id = new Guid("e0f1a2b3-4567-8901-2345-f0123456789a"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident F's note.",
                            ResidentId = new Guid("f5a6b7c8-9012-3456-789a-bcdef0123456")
                        },
                        new
                        {
                            Id = new Guid("f1a2b3c4-5678-9012-3456-0123456789ab"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident GA's note.",
                            ResidentId = new Guid("a6b7c8d9-0123-4567-89ab-cdef01234567")
                        },
                        new
                        {
                            Id = new Guid("a2b3c4d5-6789-0123-4567-123456789abc"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident H's note.",
                            ResidentId = new Guid("b7c8d9e0-1234-5678-9abc-def012345678")
                        },
                        new
                        {
                            Id = new Guid("b3c4d5e6-7890-1234-5678-23456789abcd"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident I's note.",
                            ResidentId = new Guid("c8d9e0f1-2345-6789-abcd-ef0123456789")
                        },
                        new
                        {
                            Id = new Guid("c4d5e6f7-8901-2345-6789-3456789abcde"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident J's note.",
                            ResidentId = new Guid("d9e0f1a2-3456-789a-bcde-f01234567890")
                        },
                        new
                        {
                            Id = new Guid("d5e6f7a8-9012-3456-7890-456789abcde0"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident K's note.",
                            ResidentId = new Guid("e0f1a2b3-4567-89ab-cdef-012345678901")
                        },
                        new
                        {
                            Id = new Guid("e6f7a8b9-0123-4567-8901-56789abcde01"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident GB's note.",
                            ResidentId = new Guid("f1a2b3c4-5678-9abc-def0-123456789012")
                        },
                        new
                        {
                            Id = new Guid("f7a8b9c0-1234-5678-9012-6789abcde012"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident GB's note 2.",
                            ResidentId = new Guid("f1a2b3c4-5678-9abc-def0-123456789012")
                        });
                });

            modelBuilder.Entity("Domain.Entities.RetentionPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("LegalMinimum")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("RetentionPeriod")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .IsUnique();

                    b.ToTable("RetentionPolicies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-0000-0000-0000-000000000001"),
                            Category = 0,
                            EffectiveFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LegalMinimum = new TimeSpan(3650, 0, 0, 0, 0),
                            RetentionPeriod = new TimeSpan(3650, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("a1111111-0000-0000-0000-000000000002"),
                            Category = 1,
                            EffectiveFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LegalMinimum = new TimeSpan(730, 0, 0, 0, 0),
                            RetentionPeriod = new TimeSpan(1825, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("a1111111-0000-0000-0000-000000000003"),
                            Category = 2,
                            EffectiveFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LegalMinimum = new TimeSpan(365, 0, 0, 0, 0),
                            RetentionPeriod = new TimeSpan(1095, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("a1111111-0000-0000-0000-000000000004"),
                            Category = 3,
                            EffectiveFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LegalMinimum = new TimeSpan(90, 0, 0, 0, 0),
                            RetentionPeriod = new TimeSpan(180, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("a1111111-0000-0000-0000-000000000005"),
                            Category = 4,
                            EffectiveFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LegalMinimum = new TimeSpan(180, 0, 0, 0, 0),
                            RetentionPeriod = new TimeSpan(365, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("a1111111-0000-0000-0000-000000000006"),
                            Category = 5,
                            EffectiveFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LegalMinimum = new TimeSpan(7, 0, 0, 0, 0),
                            RetentionPeriod = new TimeSpan(30, 0, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("Domain.Entities.RetentionPolicyAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ChangedByEmployeeId")
                        .HasColumnType("char(36)");

                    b.Property<TimeSpan>("NewPeriod")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("PreviousPeriod")
                        .HasColumnType("time(6)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("RetentionPolicyId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RetentionPolicyId");

                    b.ToTable("RetentionPolicyAudits");
                });

            modelBuilder.Entity("Domain.Entities.SecurityIncident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InvestigationNotes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<Guid?>("ReportedByEmployeeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ResolvedByEmployeeId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("SecurityIncidents");
                });

            modelBuilder.Entity("Domain.Entities.StaffAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AssignmentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ShiftType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ResidentId");

                    b.ToTable("StaffAssignments");
                });

            modelBuilder.Entity("Domain.Entities.SubjectAccessRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ExportFileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("ExportGeneratedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FulfilledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("FulfilledByEmployeeId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("RequestedByEmployeeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ScopeOptions")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("FulfilledAt");

                    b.HasIndex("ResidentId");

                    b.ToTable("SubjectAccessRequests");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<int?>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3a21f8e1-885b-4394-abf0-ed0baeea239b"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3f2de00f-6d2c-4f3d-a4e6-0c0a0b1fbd1c",
                            Email = "PederRasmussen@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PEDERRASMUSSEN@EXAMPLE.COM",
                            NormalizedUserName = "PEDERRASMUSSEN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENTTirmPX3De5hmV/oT+Swwtap0kZ84qqwwOniU4UL53GHWkxgaySIGzevzhBBGmGw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d7cefa32-0e20-4ccc-b2e3-e092b6fa4d6b",
                            TwoFactorEnabled = false,
                            UserName = "pederrasmussen@example.com"
                        },
                        new
                        {
                            Id = new Guid("4711a300-711e-4132-86d4-cafd3f11deec"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "91ce28f7-0cde-4102-8822-410d6d51a011",
                            Email = "SanneJohansen@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SANNEJOHANSEN@EXAMPLE.COM",
                            NormalizedUserName = "SANNEJOHANSEN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENF2JKDK/0VWrkQpjgbotpODUrbQnhHb9IStKVMqBGx0ddH1gxQcX0Kfbw0WZftMJg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "91b36f1f-fc24-43df-9c27-541cca61aaed",
                            TwoFactorEnabled = false,
                            UserName = "sannejohansen@example.com"
                        },
                        new
                        {
                            Id = new Guid("30cffcf9-5784-4fa9-9c10-c013ef3faf16"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f67063f6-8396-4fda-acb9-f8828704a5b8",
                            Email = "ThorDanrsøn@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "THORDANRSØN@EXAMPLE.COM",
                            NormalizedUserName = "THORDANRSØN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHhZqSVVwABEaci/cdKiZtNkgWYtLVqXbqFBCNZIV4dqfQDL16QCSrotswlj69SrUg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c3abc4c0-86fe-4ef7-b5e4-7ee983137035",
                            TwoFactorEnabled = false,
                            UserName = "thordanrsøn@example.com"
                        },
                        new
                        {
                            Id = new Guid("37155b80-7111-422a-aba6-89d7070f1644"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "db2dea37-cbf4-41c1-bc59-73caee8a4e19",
                            Email = "PerNielsen@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PERNIELSEN@EXAMPLE.COM",
                            NormalizedUserName = "PERNIELSEN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBL8M5DmvJzuQHt9PpsMEkme+soEFK8FDtbeExPk01Mvs3RUnwJnGlsmfR3F9mMwWQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8f471647-de42-45a4-a1e7-19d2a64d4fad",
                            TwoFactorEnabled = false,
                            UserName = "pernielsen@example.com"
                        },
                        new
                        {
                            Id = new Guid("b836e975-e775-48bc-8b84-5d2bdd5bd87a"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "464bbb79-d13e-4334-947f-623592a9e3ab",
                            Email = "AndersJensen@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ANDERSJENSEN@EXAMPLE.COM",
                            NormalizedUserName = "ANDERSJENSEN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDQ4ibv32SQaSnNOk25S6jkob7SqrXYx2X+SiwdNh7cGDwY+gAMdwjkYAGFs+jT1Ng==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e60422b7-3153-4119-b618-1fb81cfcba64",
                            TwoFactorEnabled = false,
                            UserName = "andersjensen@example.com"
                        },
                        new
                        {
                            Id = new Guid("48245a9c-f2a5-4e8f-9554-b6acc9206d37"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8b5cdde3-1a6b-41d9-94b0-692680149979",
                            Email = "KasperHolm@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "KASPERHOLM@EXAMPLE.COM",
                            NormalizedUserName = "KASPERHOLM@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMPle04qWx0hcDeIBXXKVes08Cj6PAWCOsMFEJrpw9jM4Qnp9AIMTNdf+NSyULPGgw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5e9a0fd8-e3f1-4d66-afe3-77e1e83a7446",
                            TwoFactorEnabled = false,
                            UserName = "kasperholm@example.com"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c0ffee00-dead-beef-cafe-000000000001",
                            Email = "dashboard@slottet.dk",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DASHBOARD@SLOTTET.DK",
                            NormalizedUserName = "DASHBOARD@SLOTTET.DK",
                            PasswordHash = "AQAAAAEAACcQAAAAEEGYLbEVvDkMGpWxvBizSJSS95uMkciMO3NcZV2yi+7goH8chkCEacnfd4IcKtrBaQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c0ffee00-dead-beef-cafe-000000000002",
                            TwoFactorEnabled = false,
                            UserName = "dashboard@slottet.dk"
                        });
                });

            modelBuilder.Entity("Infrastructure.Data.Persistent.Views.MedicineStatusView", b =>
                {
                    b.Property<int>("ActiveMedicines")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("char(36)");

                    b.ToTable((string)null);

                    b.ToView("medicinestatusview", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Persistent.Views.PainkillerStatusView", b =>
                {
                    b.Property<int>("ActivePainkillers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("char(36)");

                    b.ToTable((string)null);

                    b.ToView("painkillerstatusview", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Persistent.Views.PhoneAssignmentView", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable((string)null);

                    b.ToView("vwPhoneAssignment", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Persistent.Views.ResidentNoteView", b =>
                {
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EditedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("char(36)");

                    b.ToTable((string)null);

                    b.ToView("vwResidentNote", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("fabc2277-7992-491b-ae4a-bc78f8de56aa"),
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("d1c9e8b5-3f4a-4c2e-9a1b-5e6f7a8b9c0d"),
                            Name = "superuser",
                            NormalizedName = "SUPERUSER"
                        },
                        new
                        {
                            Id = new Guid("ee697c76-947a-4fe2-8b14-40194c30bdae"),
                            Name = "caretaker",
                            NormalizedName = "CARETAKER"
                        },
                        new
                        {
                            Id = new Guid("d0a5b0a1-0000-4000-8000-000000000001"),
                            Name = "dashboard",
                            NormalizedName = "DASHBOARD"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 2,
                            ClaimType = "permission",
                            ClaimValue = "view:medicine",
                            RoleId = new Guid("ee697c76-947a-4fe2-8b14-40194c30bdae")
                        },
                        new
                        {
                            Id = 1,
                            ClaimType = "permission",
                            ClaimValue = "manage:residents",
                            RoleId = new Guid("fabc2277-7992-491b-ae4a-bc78f8de56aa")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            ClaimType = "permission",
                            ClaimValue = "manage:residents",
                            UserId = new Guid("4711a300-711e-4132-86d4-cafd3f11deec")
                        },
                        new
                        {
                            Id = 1002,
                            ClaimType = "permission",
                            ClaimValue = "department:slottet:basic",
                            UserId = new Guid("30cffcf9-5784-4fa9-9c10-c013ef3faf16")
                        },
                        new
                        {
                            Id = 1003,
                            ClaimType = "permission",
                            ClaimValue = "department:skoven:basic",
                            UserId = new Guid("37155b80-7111-422a-aba6-89d7070f1644")
                        },
                        new
                        {
                            Id = 1004,
                            ClaimType = "permission",
                            ClaimValue = "department:skoven:basic",
                            UserId = new Guid("b836e975-e775-48bc-8b84-5d2bdd5bd87a")
                        },
                        new
                        {
                            Id = 1005,
                            ClaimType = "permission",
                            ClaimValue = "department:marken:basic",
                            UserId = new Guid("48245a9c-f2a5-4e8f-9554-b6acc9206d37")
                        },
                        new
                        {
                            Id = 1006,
                            ClaimType = "permission",
                            ClaimValue = "department:slottet:basic",
                            UserId = new Guid("4711a300-711e-4132-86d4-cafd3f11deec")
                        },
                        new
                        {
                            Id = 1007,
                            ClaimType = "permission",
                            ClaimValue = "department:all:view",
                            UserId = new Guid("3a21f8e1-885b-4394-abf0-ed0baeea239b")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("3a21f8e1-885b-4394-abf0-ed0baeea239b"),
                            RoleId = new Guid("fabc2277-7992-491b-ae4a-bc78f8de56aa")
                        },
                        new
                        {
                            UserId = new Guid("4711a300-711e-4132-86d4-cafd3f11deec"),
                            RoleId = new Guid("d1c9e8b5-3f4a-4c2e-9a1b-5e6f7a8b9c0d")
                        },
                        new
                        {
                            UserId = new Guid("30cffcf9-5784-4fa9-9c10-c013ef3faf16"),
                            RoleId = new Guid("ee697c76-947a-4fe2-8b14-40194c30bdae")
                        },
                        new
                        {
                            UserId = new Guid("37155b80-7111-422a-aba6-89d7070f1644"),
                            RoleId = new Guid("ee697c76-947a-4fe2-8b14-40194c30bdae")
                        },
                        new
                        {
                            UserId = new Guid("b836e975-e775-48bc-8b84-5d2bdd5bd87a"),
                            RoleId = new Guid("ee697c76-947a-4fe2-8b14-40194c30bdae")
                        },
                        new
                        {
                            UserId = new Guid("48245a9c-f2a5-4e8f-9554-b6acc9206d37"),
                            RoleId = new Guid("ee697c76-947a-4fe2-8b14-40194c30bdae")
                        },
                        new
                        {
                            UserId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            RoleId = new Guid("d0a5b0a1-0000-4000-8000-000000000001")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AnonymizationCandidate", b =>
                {
                    b.HasOne("Domain.Entities.Resident", "Resident")
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.RetentionPolicy", "RetentionPolicy")
                        .WithMany("Candidates")
                        .HasForeignKey("RetentionPolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resident");

                    b.Navigation("RetentionPolicy");
                });

            modelBuilder.Entity("Domain.Entities.ChangeDetail", b =>
                {
                    b.HasOne("Domain.Entities.AuditEntry", null)
                        .WithMany("ChangeDetails")
                        .HasForeignKey("AuditEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Employee", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.MedicineRecord", b =>
                {
                    b.HasOne("Domain.Entities.Resident", null)
                        .WithMany("Medicines")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.PainkillerRecord", b =>
                {
                    b.HasOne("Domain.Entities.Resident", null)
                        .WithMany("Painkillers")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.ResidentNote", b =>
                {
                    b.HasOne("Domain.Entities.Resident", null)
                        .WithMany("Notes")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.RetentionPolicyAudit", b =>
                {
                    b.HasOne("Domain.Entities.RetentionPolicy", "RetentionPolicy")
                        .WithMany("AuditHistory")
                        .HasForeignKey("RetentionPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RetentionPolicy");
                });

            modelBuilder.Entity("Domain.Entities.StaffAssignment", b =>
                {
                    b.HasOne("Domain.Entities.Employee", "Employee")
                        .WithMany("StaffAssignments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Resident", "Resident")
                        .WithMany("StaffAssignments")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("Domain.Entities.SubjectAccessRequest", b =>
                {
                    b.HasOne("Domain.Entities.Resident", "Resident")
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.AuditEntry", b =>
                {
                    b.Navigation("ChangeDetails");
                });

            modelBuilder.Entity("Domain.Entities.Employee", b =>
                {
                    b.Navigation("StaffAssignments");
                });

            modelBuilder.Entity("Domain.Entities.Resident", b =>
                {
                    b.Navigation("Medicines");

                    b.Navigation("Notes");

                    b.Navigation("Painkillers");

                    b.Navigation("StaffAssignments");
                });

            modelBuilder.Entity("Domain.Entities.RetentionPolicy", b =>
                {
                    b.Navigation("AuditHistory");

                    b.Navigation("Candidates");
                });
#pragma warning restore 612, 618
        }
    }
}
